config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"

  get '/resorts', to: 'resorts#index'

  get 'snotel', to: 'snotel#index', as: :snotel_index
  get 'snotel/:station_name', to: 'snotel#show', as: :snotel_station

  get 'snotel/:station_name/temperature_chart', to: 'snotel#temperature_chart', as: 'temperature_chart'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lift.rb
class Lift < ApplicationRecord
  belongs_to :resort
  has_many :trails
end

app/models/resort.rb
class Resort < ApplicationRecord
    has_many :lifts
end

app/models/snotel_weather_observation.rb
class SnotelWeatherObservation < ApplicationRecord
  belongs_to :snotel_weather_station, foreign_key: 'snotel_weather_station_id', primary_key: 'name'
end

app/models/snotel_weather_station.rb
class SnotelWeatherStation < ApplicationRecord
    self.primary_key = 'name'
    has_many :snotel_weather_observations, foreign_key: 'snotel_weather_station_id', primary_key: 'name'
end

app/models/trail.rb
class Trail < ApplicationRecord
  belongs_to :lift
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
    def index
      @resorts = Resort.includes(lifts: :trails).all
    end
  end
  

app/controllers/snotel_controller.rb
class SnotelController < ApplicationController
    before_action :find_station, only: [:show, :temperature_chart]
  
    def index
      @stations = SnotelWeatherStation.all
    end
  
    def show
      if @station
        @observations = @station.snotel_weather_observations
      else
        # Handle the case where the station is not found
        flash[:alert] = "Station not found."
        redirect_to snotel_index_path
      end
    end
  
    # def temperature_chart
    #   if @station
    #     # Fetch observations for the last 7 days and order them
    #     @observations = @station.snotel_weather_observations
    #                             .where('time > ?', 7.days.ago)
    #                             .order(:time)
    #   else
    #     flash[:alert] = "Station not found."
    #     redirect_to snotel_index_path
    #   end
  
    #   # Additional check in case there are no observations in the last 7 days
    #   if @observations.blank?
    #     flash[:alert] = "No recent observations found for the station."
    #     redirect_to snotel_index_path
    #   end
    # end
  
    private
  
    def find_station
      @station = SnotelWeatherStation.find_by(name: params[:station_name])
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resorts_helper.rb
module ResortsHelper
end

app/helpers/weather_observations_helper.rb
module WeatherObservationsHelper
    def calculate_height(temp_fahrenheit)
      # Adjust the formula based on the Fahrenheit range you expect
      # Assuming max temperature is 120°F and height of SVG is 100
      (temp_fahrenheit.to_f / 120) * 100
    end
  
    def calculate_color(temp_fahrenheit)
      # Simple logic to change color based on temperature (Fahrenheit)
      if temp_fahrenheit < 50
        '#add8e6' # Light blue for colder temperatures
      elsif temp_fahrenheit < 80
        '#ffff00' # Yellow for mild temperatures
      else
        '#ff4500' # Orange-red for hot temperatures
      end
    end
  end
  

app/views/home/coming_soon.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Your App Name</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
</head>
<body>
    <h1>Coming soon...</h1>
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>snowdata.app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
</head>
<body>
    <h1>Coming soon...</h1>
</body>
</html>

app/views/layouts/_footer.html.erb
<footer class="app-footer">
  <div class="container">
    <p class="text-center"> </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!--

<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <div class="container">
    <%= link_to 'snowdata.app', root_path, class: 'navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white' %>
    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'app-link' %>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: 'app-link' %>
      <%= link_to 'Register', new_user_registration_path, class: 'app-link' %>
    <% end %>
  </div>
</header>

-->


<header class="navbar sticky-top bg-dark flex-md-nowrap p-0 shadow" data-bs-theme="dark" style="">
  <%= link_to 'snowdata.app', root_path, class: 'navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white' %>

  <!--

  <ul class="navbar-nav flex-row d-md-none">
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle search">
        <svg class="bi"><use xlink:href="#search"></use></svg>
      </button>
    </li>
    <li class="nav-item text-nowrap">
      <button class="nav-link px-3 text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <svg class="bi"><use xlink:href="#list"></use></svg>
      </button>
    </li>
  </ul>

  -->

  <%= link_to 'All Stations', snotel_index_path %>

  <div id="navbarSearch" class="navbar-search w-100 collapse" style="">
    <input class="form-control w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snowdata</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.10.0/chart.min.js" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body class="<%= controller_name %>">

    <%= render 'layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/resorts/index.html.erb
<% @resorts.each do |resort| %>
    <div class="resort">
        <h2><%= resort.name %></h2>
        <ul>
        <% resort.lifts.each do |lift| %>
            <li>
            <h3><%= lift.name %></h3>
            <div class="open-status <%= lift.status %>"></div>
            <span class="status-text"><%= lift.status.capitalize %></span>
            <ul>
                <% lift.trails.each do |trail| %>
                <li>
                    <span><%= trail.name %></span>
                    <div class="open-status <%= trail.status %>"></div>
                    <span class="status-text"><%= trail.status.capitalize %></span>
                </li>
                <% end %>
            </ul>
            </li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/snotel/_graph.html.erb
<svg class="attribute-graph" height="100" width="100%">
  <% observations.each_with_index do |observation, index| %>
    <% value = observation.send(attribute) %>
    <% height = calculate_height(value) %>
    <% color = calculate_color(value) %>
    <rect x="<%= index * (100.0 / observations.count) %>%" 
          y="<%= 100 - height %>" 
          width="<%= 100.0 / observations.count %>%" 
          height="<%= height %>" 
          fill="<%= color %>" />
  <% end %>
</svg>

app/views/snotel/index.html.erb
<h1>Snotel Weather Stations</h1>

<ul>
  <% @stations.each do |station| %>
    <li>
      <%= link_to station.name, snotel_station_path(station.name.parameterize) %>
    </li>
  <% end %>
</ul>

app/views/snotel/show.html.erb
<h1><%= @station.name %> Observations</h1>

<% if @observations.any? %>

  <div class="graphs-container">
    <% attributes = %w[temp max_temp min_temp wind_speed wind_direction wind_gust_speed melted_precipitation_1hr snow_height snow_water_equivalent] %>

    <% attributes.each do |attribute| %>
      <div class="graph-section">
        <h3><%= attribute.titleize %></h3>
        <%= render 'graph', observations: @observations, attribute: attribute %>
      </div>
    <% end %>
  </div>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Temp</th>
        <th>MxTp</th>
        <th>MnTp</th>
        <th>Wind Spd</th>
        <th>Wind Dir</th>
        <th>Gust Spd</th>
        <th>Pcp1</th>
        <th>Snow Depth</th>
        <th>SWE</th>
        <!-- Add more headers as needed -->
      </tr>
    </thead>
    <tbody>
      <% @observations.each do |observation| %>
        <tr>
          <td><%= observation.date %></td>
          <td><%= observation.time %></td>
          <td><%= observation.temp %></td>
          <td><%= observation.max_temp %></td>
          <td><%= observation.min_temp %></td>
          <td><%= observation.wind_speed %></td>
          <td><%= observation.wind_direction %></td>
          <td><%= observation.wind_gust_speed %></td>
          <td><%= observation.melted_precipitation_1hr %></td>
          <td><%= observation.snow_height %></td>
          <td><%= observation.snow_water_equivalent %></td>
          <!-- Add more cells as needed -->
        </tr>
      <% end %>
    </tbody>
  </table>


  <%= link_to 'Temperature Chart', temperature_chart_path(@station.name) %>


<% else %>
  <p>No observations available for this station.</p>
<% end %>

app/views/snotel/temperature_chart.html.erb
<h1><%= @station.name %> Temperature Chart</h1>

<% if @observations.present? %>
  <% chart_data = @observations.map { |obs| [obs[:time], obs[:temp]] } %>
  <%= line_chart chart_data, discrete: true, height: '400px', xtitle: 'Time', ytitle: 'Temperature (°F)' %>
<% else %>
  <p>No observations found for the station.</p>
<% end %>